[build]
  functions = "functions"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31557600"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31557600"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31557600"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31557600"
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31557600"
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31557600"
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31557600"